routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use Database\Seeders\AttendanceSeeder;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class,"index"])->name('home');


Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();
Route::resource('/students', App\Http\Controllers\StudentController::class);


Route::resource('/courses', App\Http\Controllers\CourseController::class);


Route::get('/learndays/show_deleted', [App\Http\Controllers\LearnDayController::class, 'show_deleted'])->name('learndays.show_deleted');
Route::put('/learndays/restore/{learnday}', [App\Http\Controllers\LearnDayController::class, 'restore'])->name('learndays.restore')->withTrashed();
Route::resource('/learndays', App\Http\Controllers\LearnDayController::class);


Route::get('/attendances/show_deleted', [App\Http\Controllers\AttendanceController::class, 'show_deleted'])->name('attendances.show_deleted');
Route::put('/attendances/restore/{attendance}', [App\Http\Controllers\AttendanceController::class, 'restore'])->name('attendances.restore')->withTrashed();


Route::resource('/attendances', App\Http\Controllers\AttendanceController::class);

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

use Illuminate\Database\Eloquent\SoftDeletes;

class Attendance extends Model
{
    use HasFactory;

    protected $fillable = [
        'status',
        'learnday_id',
        'student_id'
    ];

    public function learnday(): BelongsTo
    {
        return $this->belongsTo(Learnday::class);
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(Student::class);
    }
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreattendanceRequest;
use App\Http\Requests\UpdateattendanceRequest;
use App\Models\attendance;
use App\Models\Learnday;
use Illuminate\Http\Request;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store($learnday)
    {
        dd($learnday);
        
    }

    /**
     * Display the specified resource.
     */
    public function show(attendance $attendance)
    {
        $attendance = attendance::find($attendance);
        return view('attendances.show', ['attendances' => $attendance ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(attendance $attendance)
    {
        

        $attendance = attendance::find($attendance);
        return view('attendance.edit', ['attendances' => $attendance]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateattendanceRequest $request, attendance $attendance)
    {
        $attendance->update($request->all());

        return redirect()->route('attendances.index')->with('success', 'The learn day was updated successfully.');
    }
    

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(attendance $attendance)
    {
        $attendance = attendance::find($attendance);
        $attendance->delete();
        return back()->with('success', 'Successfully deleted the learn day: ' . $attendance->learnday->course->title . '.');
    }

    // saját funkció

  /*   public function class_index($learndays)
    {
        return view('attendances.index', compact('learndays'));
    } */

    public function massupdate(Request $request, Learnday $learnday)
    {
        $students = collect();
        $studentsNew = $learnday->attendances; 
        
        
        foreach ($studentsNew as $key => $value) {
            $students->push($value->student);
        }
        
        foreach ($students as $key => $student) {
            $studentStatus = $student->attendances->where('learnday_id', $learnday->id)->first()->status; 

            
            if ( array_key_exists('status'.$student->id, $request->all() )  ) {
                $studentInputStatus = $request->all()['status'.$student->id]; 

                if ($studentStatus != $studentInputStatus) 
                {                    
                    
                    Attendance::where('student_id', $student->id)->where('learnday_id', $learnday->id)->update([
                        'status' => $studentInputStatus,
                    ]);
                }
            }
        }
        return back()->with('success', 'Successfully saved the changes.');
    }

}

resources/views/attendances/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary bg-dark">
                <div class="card-body text-white">
                    <h4 class="card-title">Edit a Learn Day named: {{ $attendances->status }}</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                            <strong>Holy guacamole!</strong>
                            <p>{{ Session::get('success') }}</p>
                        </div>
                    @endif

                    <form action="{{ route('learndays.update', $attendances ) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label>
                            <input type="text" name="status" id="status"
                                class="form-control @if ($errors->has('status')) border border-danger @endif"
                                placeholder="status of the Day" aria-describedby="helpId"
                                value="{{ old('status', $attendances->status) }}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('title') }}</small>
                            @else
                                <small id="helpId" class="text-white">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="date" class="form-label">Date</label>
                            <input type="text" name="date" id="date" class="form-control" placeholder="0000-00-00" aria-describedby="helpId" maxlength="255" value="{{ old('date', $learndays->date) }}">
                            
                            <small id="helpId" class="text-white">Date of the Learn Day</small>
                        </div>
                        <div class="mb-3">
                            <label for="course" class="form-label">Class</label>
                            <select class="form-select" aria-label="Default select example" name="course_id">
                                <option hidden>Classes</option>
                                @foreach ($courses as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                            <small id="helpId" class="text-white">For which class the learn day is</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/attendances/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            <div class="table-responsive-xl">
                <table class="table table-dark" id="studentTable">
                    <thead>
                        <tr>
                            <th scope="col">Class</th>
                            <th scope="col">Learn Day</th>
                            <th></th>
                            <th></th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($attendances as $item)
                            <tr class="">
                              <td scope="row">{{ $item->learnday->course->name}}</td>  
                                <td>{{ $item->learnday->date }}</td> 
                                <td>
                                    <form action="{{ route('attendances.edit', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>

                                    <form action="{{ route('attendances.show', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show data</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection

resources/views/attendances/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card border-secondary bg-dark">
            <div class="card-body text-white">
                @foreach ($attendances as $item)
                     <h4 class="card-title">{{ $item->learnday->title }}</h4>
                @endforeach
               
                @foreach ($attendances as $item)

                <p>Name of the Student: {{$item->student->name}}</p>
                @endforeach
                
                
                
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

@endsection

resources/views/attendances/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1>Deleted Learn Day(s)</h1>
            <div class="table-responsive-xl">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Learn Day title</th>
                            <th scope="col">Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($learndays as $item)
                            <tr class="">
                                <td scope="row">{{$item->title}}</td>
                                <td>{{$item->date}}</td>
                                <td>
                                    <form action="{{ route('learndays.restore', $item) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection